[project]
name = "mlflow-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.10",
    "mlflow>=2.21.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
